version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: GH_Miner_rpassword
      MYSQL_DATABASE: GH_Miner_db
      MYSQL_USER: GH_Miner_usr
      MYSQL_PASSWORD: GH_Miner_pswrd
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
  ghminer:
    build: .
    image: ncsu/ghminer:latest
    container_name: ghminer
    environment:
      DEBUG: true
      SECRET_KEY: your_secret_key_here
      GITHUB_OAUTH_CLIENT_ID: 106c8f10e10a59a7d9f8
      GITHUB_OAUTH_CLIENT_SECRET: eedf85ff88d3a1f23fee6c1a2cf91b6cb750c134
      # these must match the mysql params
      MYSQL_DATABASE_USER: GH_Miner_usr
      MYSQL_DATABASE_PASSWORD: GH_Miner_pswrd
      MYSQL_DATABASE_DB: GH_Miner_db
      MYSQL_DATABASE_HOST: my-mysql-container:3306
      SQLALCHEMY_TRACK_MODIFICATIONS: false
    ports:
      - "5000:5000"
    depends_on:
      - mysql
