version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: GH_Miner_rpassword
      MYSQL_DATABASE: GH_Miner_db
      MYSQL_USER: GH_Miner_usr
      MYSQL_PASSWORD: GH_Miner_pswrd
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
