"""Initial migration

Revision ID: cbc87a8ce2b9
Revises: 
Create Date: 2024-01-31 17:45:38.871600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc87a8ce2b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('github_token', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('git_hub_user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('github_login', sa.String(length=100), nullable=False),
    sa.Column('semester', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lifetime', sa.Integer(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('period', sa.Integer(), nullable=True),
    sa.Column('private_contributions', sa.Integer(), nullable=True),
    sa.Column('commits', sa.Integer(), nullable=True),
    sa.Column('issues', sa.Integer(), nullable=True),
    sa.Column('gists', sa.Integer(), nullable=True),
    sa.Column('prs', sa.Integer(), nullable=True),
    sa.Column('pr_reviews', sa.Integer(), nullable=True),
    sa.Column('repository_discussions', sa.Integer(), nullable=True),
    sa.Column('commit_comments', sa.Integer(), nullable=True),
    sa.Column('issue_comments', sa.Integer(), nullable=True),
    sa.Column('gist_comments', sa.Integer(), nullable=True),
    sa.Column('repository_discussion_comments', sa.Integer(), nullable=True),
    sa.Column('repos', sa.Integer(), nullable=True),
    sa.Column('a_count', sa.Integer(), nullable=True),
    sa.Column('a_fork_count', sa.Integer(), nullable=True),
    sa.Column('a_stargazer_count', sa.Integer(), nullable=True),
    sa.Column('a_watcher_count', sa.Integer(), nullable=True),
    sa.Column('a_total_size', sa.BigInteger(), nullable=True),
    sa.Column('a_langs', sa.Integer(), nullable=True),
    sa.Column('b_count', sa.Integer(), nullable=True),
    sa.Column('b_fork_count', sa.Integer(), nullable=True),
    sa.Column('b_stargazer_count', sa.Integer(), nullable=True),
    sa.Column('b_watcher_count', sa.Integer(), nullable=True),
    sa.Column('b_total_size', sa.BigInteger(), nullable=True),
    sa.Column('b_langs', sa.Integer(), nullable=True),
    sa.Column('c_total_count', sa.Integer(), nullable=True),
    sa.Column('c_fork_count', sa.Integer(), nullable=True),
    sa.Column('c_stargazer_count', sa.Integer(), nullable=True),
    sa.Column('c_watcher_count', sa.Integer(), nullable=True),
    sa.Column('c_total_size', sa.BigInteger(), nullable=True),
    sa.Column('c_langs', sa.Integer(), nullable=True),
    sa.Column('d_total_count', sa.Integer(), nullable=True),
    sa.Column('d_fork_count', sa.Integer(), nullable=True),
    sa.Column('d_stargazer_count', sa.Integer(), nullable=True),
    sa.Column('d_watcher_count', sa.Integer(), nullable=True),
    sa.Column('d_total_size', sa.BigInteger(), nullable=True),
    sa.Column('d_langs', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_hub_user_data')
    op.drop_table('user')
    # ### end Alembic commands ###
