on:
    pull_request:
        branches:
          - main

jobs:
    lint-and-test:
        name: Lint and Test
        runs-on: ubuntu
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Run integration tests
              run: |
                python -m pytest -s tests/integration_tests/integration_test.py
